### ISSUE TITLE
Does not work with WiFi-only networking (no cell data plan)

### ISSUE THREAD

**Issue by amandamana** [dlevi309/Conditional#1]
Thanks for this!

I have an issue (on iOS 14.7.1) where apps do not get added to the settings Cellular submenu I think because my device does not have cellular data (just voice & text on the SIM plan). I believe new apps usually show up in this list only after they've been launched and attempt to use the cellular data network. Built-in apps (Appstore, Books, Facetime, etc...) are already propagated and can have their WiFi access disabled, but no apps that I install show up.

Any solution for this?

**Comment by dlevi309** [comment]
Hi there,

Unfortunately, nothing can be done about this because the hook relies on the device supporting cellular data. Although; there’s a great tweak that should work just fine for your situation, it’s called [AirKeeper](https://github.com/udevsharold/airkeeper)

Best Regards,
Daniel

**Comment by amandamana** [comment]
Amazing, thank you! Works great.
